// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"favorite/ent/predicate"
	"favorite/ent/reluserproject"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RelUserProjectDelete is the builder for deleting a RelUserProject entity.
type RelUserProjectDelete struct {
	config
	hooks    []Hook
	mutation *RelUserProjectMutation
}

// Where appends a list predicates to the RelUserProjectDelete builder.
func (rupd *RelUserProjectDelete) Where(ps ...predicate.RelUserProject) *RelUserProjectDelete {
	rupd.mutation.Where(ps...)
	return rupd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (rupd *RelUserProjectDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(rupd.hooks) == 0 {
		affected, err = rupd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RelUserProjectMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rupd.mutation = mutation
			affected, err = rupd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(rupd.hooks) - 1; i >= 0; i-- {
			if rupd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rupd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rupd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (rupd *RelUserProjectDelete) ExecX(ctx context.Context) int {
	n, err := rupd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (rupd *RelUserProjectDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: reluserproject.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: reluserproject.FieldID,
			},
		},
	}
	if ps := rupd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, rupd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// RelUserProjectDeleteOne is the builder for deleting a single RelUserProject entity.
type RelUserProjectDeleteOne struct {
	rupd *RelUserProjectDelete
}

// Exec executes the deletion query.
func (rupdo *RelUserProjectDeleteOne) Exec(ctx context.Context) error {
	n, err := rupdo.rupd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{reluserproject.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (rupdo *RelUserProjectDeleteOne) ExecX(ctx context.Context) {
	rupdo.rupd.ExecX(ctx)
}
