// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"favorite/ent/predicate"
	"favorite/ent/reluserproject"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RelUserProjectQuery is the builder for querying RelUserProject entities.
type RelUserProjectQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.RelUserProject
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RelUserProjectQuery builder.
func (rupq *RelUserProjectQuery) Where(ps ...predicate.RelUserProject) *RelUserProjectQuery {
	rupq.predicates = append(rupq.predicates, ps...)
	return rupq
}

// Limit adds a limit step to the query.
func (rupq *RelUserProjectQuery) Limit(limit int) *RelUserProjectQuery {
	rupq.limit = &limit
	return rupq
}

// Offset adds an offset step to the query.
func (rupq *RelUserProjectQuery) Offset(offset int) *RelUserProjectQuery {
	rupq.offset = &offset
	return rupq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rupq *RelUserProjectQuery) Unique(unique bool) *RelUserProjectQuery {
	rupq.unique = &unique
	return rupq
}

// Order adds an order step to the query.
func (rupq *RelUserProjectQuery) Order(o ...OrderFunc) *RelUserProjectQuery {
	rupq.order = append(rupq.order, o...)
	return rupq
}

// First returns the first RelUserProject entity from the query.
// Returns a *NotFoundError when no RelUserProject was found.
func (rupq *RelUserProjectQuery) First(ctx context.Context) (*RelUserProject, error) {
	nodes, err := rupq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{reluserproject.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rupq *RelUserProjectQuery) FirstX(ctx context.Context) *RelUserProject {
	node, err := rupq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RelUserProject ID from the query.
// Returns a *NotFoundError when no RelUserProject ID was found.
func (rupq *RelUserProjectQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = rupq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{reluserproject.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rupq *RelUserProjectQuery) FirstIDX(ctx context.Context) string {
	id, err := rupq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RelUserProject entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RelUserProject entity is found.
// Returns a *NotFoundError when no RelUserProject entities are found.
func (rupq *RelUserProjectQuery) Only(ctx context.Context) (*RelUserProject, error) {
	nodes, err := rupq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{reluserproject.Label}
	default:
		return nil, &NotSingularError{reluserproject.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rupq *RelUserProjectQuery) OnlyX(ctx context.Context) *RelUserProject {
	node, err := rupq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RelUserProject ID in the query.
// Returns a *NotSingularError when more than one RelUserProject ID is found.
// Returns a *NotFoundError when no entities are found.
func (rupq *RelUserProjectQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = rupq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{reluserproject.Label}
	default:
		err = &NotSingularError{reluserproject.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rupq *RelUserProjectQuery) OnlyIDX(ctx context.Context) string {
	id, err := rupq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RelUserProjects.
func (rupq *RelUserProjectQuery) All(ctx context.Context) ([]*RelUserProject, error) {
	if err := rupq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return rupq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (rupq *RelUserProjectQuery) AllX(ctx context.Context) []*RelUserProject {
	nodes, err := rupq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RelUserProject IDs.
func (rupq *RelUserProjectQuery) IDs(ctx context.Context) ([]string, error) {
	var ids []string
	if err := rupq.Select(reluserproject.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rupq *RelUserProjectQuery) IDsX(ctx context.Context) []string {
	ids, err := rupq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rupq *RelUserProjectQuery) Count(ctx context.Context) (int, error) {
	if err := rupq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return rupq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (rupq *RelUserProjectQuery) CountX(ctx context.Context) int {
	count, err := rupq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rupq *RelUserProjectQuery) Exist(ctx context.Context) (bool, error) {
	if err := rupq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return rupq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (rupq *RelUserProjectQuery) ExistX(ctx context.Context) bool {
	exist, err := rupq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RelUserProjectQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rupq *RelUserProjectQuery) Clone() *RelUserProjectQuery {
	if rupq == nil {
		return nil
	}
	return &RelUserProjectQuery{
		config:     rupq.config,
		limit:      rupq.limit,
		offset:     rupq.offset,
		order:      append([]OrderFunc{}, rupq.order...),
		predicates: append([]predicate.RelUserProject{}, rupq.predicates...),
		// clone intermediate query.
		sql:    rupq.sql.Clone(),
		path:   rupq.path,
		unique: rupq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UUID string `json:"uuid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RelUserProject.Query().
//		GroupBy(reluserproject.FieldUUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rupq *RelUserProjectQuery) GroupBy(field string, fields ...string) *RelUserProjectGroupBy {
	grbuild := &RelUserProjectGroupBy{config: rupq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := rupq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return rupq.sqlQuery(ctx), nil
	}
	grbuild.label = reluserproject.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UUID string `json:"uuid,omitempty"`
//	}
//
//	client.RelUserProject.Query().
//		Select(reluserproject.FieldUUID).
//		Scan(ctx, &v)
func (rupq *RelUserProjectQuery) Select(fields ...string) *RelUserProjectSelect {
	rupq.fields = append(rupq.fields, fields...)
	selbuild := &RelUserProjectSelect{RelUserProjectQuery: rupq}
	selbuild.label = reluserproject.Label
	selbuild.flds, selbuild.scan = &rupq.fields, selbuild.Scan
	return selbuild
}

func (rupq *RelUserProjectQuery) prepareQuery(ctx context.Context) error {
	for _, f := range rupq.fields {
		if !reluserproject.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rupq.path != nil {
		prev, err := rupq.path(ctx)
		if err != nil {
			return err
		}
		rupq.sql = prev
	}
	return nil
}

func (rupq *RelUserProjectQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RelUserProject, error) {
	var (
		nodes = []*RelUserProject{}
		_spec = rupq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*RelUserProject).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &RelUserProject{config: rupq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rupq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (rupq *RelUserProjectQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rupq.querySpec()
	_spec.Node.Columns = rupq.fields
	if len(rupq.fields) > 0 {
		_spec.Unique = rupq.unique != nil && *rupq.unique
	}
	return sqlgraph.CountNodes(ctx, rupq.driver, _spec)
}

func (rupq *RelUserProjectQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := rupq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (rupq *RelUserProjectQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   reluserproject.Table,
			Columns: reluserproject.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: reluserproject.FieldID,
			},
		},
		From:   rupq.sql,
		Unique: true,
	}
	if unique := rupq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := rupq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reluserproject.FieldID)
		for i := range fields {
			if fields[i] != reluserproject.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rupq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rupq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rupq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rupq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rupq *RelUserProjectQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rupq.driver.Dialect())
	t1 := builder.Table(reluserproject.Table)
	columns := rupq.fields
	if len(columns) == 0 {
		columns = reluserproject.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rupq.sql != nil {
		selector = rupq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rupq.unique != nil && *rupq.unique {
		selector.Distinct()
	}
	for _, p := range rupq.predicates {
		p(selector)
	}
	for _, p := range rupq.order {
		p(selector)
	}
	if offset := rupq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rupq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RelUserProjectGroupBy is the group-by builder for RelUserProject entities.
type RelUserProjectGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rupgb *RelUserProjectGroupBy) Aggregate(fns ...AggregateFunc) *RelUserProjectGroupBy {
	rupgb.fns = append(rupgb.fns, fns...)
	return rupgb
}

// Scan applies the group-by query and scans the result into the given value.
func (rupgb *RelUserProjectGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := rupgb.path(ctx)
	if err != nil {
		return err
	}
	rupgb.sql = query
	return rupgb.sqlScan(ctx, v)
}

func (rupgb *RelUserProjectGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range rupgb.fields {
		if !reluserproject.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := rupgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rupgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (rupgb *RelUserProjectGroupBy) sqlQuery() *sql.Selector {
	selector := rupgb.sql.Select()
	aggregation := make([]string, 0, len(rupgb.fns))
	for _, fn := range rupgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(rupgb.fields)+len(rupgb.fns))
		for _, f := range rupgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(rupgb.fields...)...)
}

// RelUserProjectSelect is the builder for selecting fields of RelUserProject entities.
type RelUserProjectSelect struct {
	*RelUserProjectQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (rups *RelUserProjectSelect) Scan(ctx context.Context, v interface{}) error {
	if err := rups.prepareQuery(ctx); err != nil {
		return err
	}
	rups.sql = rups.RelUserProjectQuery.sqlQuery(ctx)
	return rups.sqlScan(ctx, v)
}

func (rups *RelUserProjectSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := rups.sql.Query()
	if err := rups.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
