// Code generated by ent, DO NOT EDIT.

package reluserproject

const (
	// Label holds the string label denoting the reluserproject type in the database.
	Label = "rel_user_project"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUUID holds the string denoting the uuid field in the database.
	FieldUUID = "uuid"
	// FieldProject holds the string denoting the project field in the database.
	FieldProject = "project"
	// FieldUser holds the string denoting the user field in the database.
	FieldUser = "user"
	// Table holds the table name of the reluserproject in the database.
	Table = "rel_user_projects"
)

// Columns holds all SQL columns for reluserproject fields.
var Columns = []string{
	FieldID,
	FieldUUID,
	FieldProject,
	FieldUser,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
