// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "uuid", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "repository", Type: field.TypeString},
		{Name: "url", Type: field.TypeString},
		{Name: "domain", Type: field.TypeString},
		{Name: "store_location", Type: field.TypeString},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
	}
	// RelUserProjectsColumns holds the columns for the "rel_user_projects" table.
	RelUserProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "uuid", Type: field.TypeString},
		{Name: "project", Type: field.TypeString},
		{Name: "user", Type: field.TypeString},
	}
	// RelUserProjectsTable holds the schema information for the "rel_user_projects" table.
	RelUserProjectsTable = &schema.Table{
		Name:       "rel_user_projects",
		Columns:    RelUserProjectsColumns,
		PrimaryKey: []*schema.Column{RelUserProjectsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "uuid", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "age", Type: field.TypeInt},
		{Name: "phone_number", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ProjectsTable,
		RelUserProjectsTable,
		UsersTable,
	}
)

func init() {
}
